before_script:
  - npm i gitfolio -g

script:
  - npm ls gitfolio
  - gitfolio build monteva

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: true
  local_dir: dist
  on:
    branch: master
