language: node_js
node_js:
  - "10" # This is the node js version

cache: npm

before_script:
  - rm -rf gitfolio
  - git clone https://github.com/imfunniee/gitfolio.git
  - cd gitfolio
  - npm install

script:
  - node ./bin/gitfolio.js build monteva --theme dark --sort star --order desc
  - ls
  - cp -a dist/. ../monteva.github.io
  - cd ..
  - rm -rf gitfolio/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: true
  on:
    branch: master
  target_branch: master
